export const MOCKUP_HOME = {
  pageShell: "w-full",
  contentRightPad: "lg:pr-[76px]",
  topBarHeight: "h-[60px]",
  searchBar: "w-[520px] h-[40px] text-sm",
  heroSection: "min-h-[488px]",
  heroContentTop: "pt-9",
  heroTextBottom: "pb-10",
  heroToFeaturedHeader: "mt-8",
  heroGrid: "lg:grid lg:items-end lg:grid-cols-[376px_1fr] lg:gap-24",
  heroTitle: "font-serif text-[48px] font-normal",
  heroSubtitle: "text-[14px] max-w-[376px]",
  ctaRow: "gap-3",
  ctaButton: "h-10 px-6 text-sm",
  sectionTitle: "text-[14px]",
  sectionChevron: "w-3.5 h-3.5",
  viewAllLink: "text-xs",
  featuredHeaderToCards: "mt-3.5",
  sectionGap: "gap-8",
  featuredCardWidth: "w-[233px]",
  surfaceCardWidth: "w-[177px]",
  featuredRowWidth: "w-[1221px]",
  selectsRowWidth: "w-[974px]",
  featuredRowGap: "gap-[14px]",
  surfaceRowGap: "gap-3",
  campusBanner: "w-[380px] min-h-[190px]",
  cardRadius: "rounded-xl",
  accentBlue: "#7EC8E3",
  accentBlueBright: "#6EB5FF",
  bg: "#05070A",
} as const;

export const HOME_IMAGE_BASE = "/images/home";
